# Generated by Django 3.0.11 on 2020-12-15 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('isolated_today_contact_with_confirmed', models.IntegerField()),
                ('isolated_today_abroad', models.IntegerField()),
                ('new_contact_with_confirmed', models.IntegerField()),
                ('new_from_abroad', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DayData')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('result_date', models.DateField()),
                ('corona_result', models.BooleanField()),
                ('lab_id', models.IntegerField()),
                ('test_for_corona_diagnosis', models.BooleanField()),
                ('is_first_Test', models.BooleanField()),
                ('test_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DayData')),
            ],
        ),
    ]
